<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Folder Include="Views\Alhan\Christmas\" />
    <Folder Include="Views\Alhan\Epiphany\" />
    <Folder Include="Views\Alhan\Great-Lent\" />
    <Folder Include="Views\Alhan\Holy-Week\" />
    <Folder Include="Views\Alhan\Kiahk\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NodaTime" Version="3.2.2" />
  </ItemGroup>

</Project>
